# -*- coding: utf-8 -*-
"""Climate_Report_Figures.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xMkM8Mf9YNDIcgoWu1kJCjV65dzL2X8F
"""

!pip install xarray netCDF4 matplotlib pandas numpy cartopy

import xarray as xr
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import cartopy.crs as ccrs
import cartopy.feature as cfeature

!pip install cdsapi

# Commented out IPython magic to ensure Python compatibility.
# %%writefile /root/.cdsapirc
# url: https://cds.climate.copernicus.eu/api
# key: b5583e7c-3eb0-4ca5-8770-fbf66ccaa767
#

!cat /root/.cdsapirc

import cdsapi

client = cdsapi.Client()

!pip install cdsapi xarray netCDF4 matplotlib cartopy numpy pandas

import cdsapi

client = cdsapi.Client()

client.retrieve(
    "reanalysis-era5-single-levels",
    {
        "product_type": "reanalysis",

        "variable": [
            "2m_temperature",
        ],

        "year": ["2025"],

        "month": [
            "01", "02", "03", "04", "05", "06",
            "07", "08", "09", "10", "11", "12"
        ],

        "day": [
            "01", "02", "03", "04", "05", "06", "07", "08", "09", "10",
            "11", "12", "13", "14", "15", "16", "17", "18", "19", "20",
            "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31"
        ],

        "time": [
            "00:00",
            "06:00",
            "12:00",
            "18:00"
        ],

        # South Caucasus
        "area": [43, 38, 38, 51],

        "data_format": "netcdf",
        "download_format": "unarchived"
    },

    "era5_south_caucasus_full_2025.nc"
)

!pip install h5netcdf netCDF4

!ls -lh
!file era5_south_caucasus_2025.nc
!mv era5_south_caucasus_2025.nc era5_south_caucasus_2025.zip
!unzip era5_south_caucasus_2025.zip -d era5_2025
!ls -lh era5_2025

import glob
import xarray as xr

files = glob.glob("era5_2025/*.nc")
print(files)

ds = xr.open_dataset(files[0])
print(ds)
print(ds.data_vars)

"""#7.1 — Seasonal Precipitation Map"""

import matplotlib.pyplot as plt
import cartopy.crs as ccrs
import cartopy.feature as cfeature


precip = ds["tp"] * 1000


seasonal_precip = precip.groupby("valid_time.season").mean()


fig = plt.figure(figsize=(10, 7))

ax = plt.axes(projection=ccrs.PlateCarree())


seasonal_precip.sel(season="DJF").plot(
    ax=ax,
    transform=ccrs.PlateCarree(),
    cmap="Blues",
    cbar_kwargs={"label": "Precipitation (mm)"}
)


ax.coastlines()
ax.add_feature(cfeature.BORDERS)


ax.set_title(
    "Figure 7.1 Seasonal Precipitation Variability\nSouth Caucasus (DJF, ERA5 2025)",
    fontsize=14
)


plt.savefig(
    "figure_7_1_seasonal_precipitation.png",
    dpi=300,
    bbox_inches="tight"
)

plt.show()

"""#7.2 Extreme Precipitation Analysis"""

import matplotlib.pyplot as plt
import cartopy.crs as ccrs
import cartopy.feature as cfeature

precip = ds["tp"] * 1000


threshold = precip.quantile(0.95)

extreme_precip = precip.where(precip > threshold)

extreme_mean = extreme_precip.mean(dim="valid_time")

fig = plt.figure(figsize=(10, 7))
ax = plt.axes(projection=ccrs.PlateCarree())

extreme_mean.plot(
    ax=ax,
    transform=ccrs.PlateCarree(),
    cmap="Reds",
    cbar_kwargs={"label": "Extreme precipitation (mm)"}
)

ax.coastlines()
ax.add_feature(cfeature.BORDERS)
ax.set_title(
    "Figure 7.2 Extreme Precipitation Analysis\nSouth Caucasus (ERA5 2025)",
    fontsize=14
)

plt.savefig(
    "figure_7_2_extreme_precipitation_2025.png",
    dpi=300,
    bbox_inches="tight"
)

plt.show()

"""#7.3 Atmospheric Moisture Transport Patterns South Caucasus


"""

import cdsapi

client = cdsapi.Client()

client.retrieve(
    "reanalysis-era5-single-levels",
    {
        "product_type": "reanalysis",
        "variable": [
            "10m_u_component_of_wind",
            "10m_v_component_of_wind"
        ],
        "year": ["2025"],
        "month": [
            "01", "02", "03", "04", "05", "06",
            "07", "08", "09", "10", "11", "12"
        ],
        "day": [
            "01", "02", "03", "04", "05", "06", "07", "08", "09", "10",
            "11", "12", "13", "14", "15", "16", "17", "18", "19", "20",
            "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31"
        ],
        "time": ["00:00", "06:00", "12:00", "18:00"],
        "area": [43, 38, 38, 51],
        "data_format": "netcdf",
        "download_format": "unarchived"
    },
    "era5_wind_2025.nc"
)

!mv era5_wind_2025.nc era5_wind_2025.zip
!unzip era5_wind_2025.zip -d era5_wind_2025

import xarray as xr

ds_wind = xr.open_dataset("era5_wind_2025.zip")
print(ds_wind)
print(ds_wind.data_vars)

import matplotlib.pyplot as plt
import cartopy.crs as ccrs
import cartopy.feature as cfeature

u = ds_wind["u10"]
v = ds_wind["v10"]

u_djf = u.groupby("valid_time.season").mean().sel(season="DJF")
v_djf = v.groupby("valid_time.season").mean().sel(season="DJF")

lon = ds_wind["longitude"]
lat = ds_wind["latitude"]

fig = plt.figure(figsize=(12, 8))
ax = plt.axes(projection=ccrs.PlateCarree())

ax.quiver(
    lon[::2],
    lat[::2],
    u_djf.values[::2, ::2],
    v_djf.values[::2, ::2],
    transform=ccrs.PlateCarree(),
    scale=150
)

ax.coastlines()
ax.add_feature(cfeature.BORDERS)

ax.set_title(
    "Figure 7.3 Atmospheric Moisture Transport Patterns\nSouth Caucasus (ERA5 2025, DJF)",
    fontsize=14
)

plt.savefig("figure_7_3_moisture_transport.png", dpi=300, bbox_inches="tight")
plt.show()

from google.colab import files
files.download("figure_7_3_moisture_transport.png")

"""#7.4 - Monthly mean"""

import xarray as xr

ds_temp = xr.open_dataset("./era5_2025/data_stream-oper_stepType-instant.nc")

print(ds_temp)
print(ds_temp.data_vars)

import matplotlib.pyplot as plt

temp = ds_temp["t2m"] - 273.15  # Kelvin → Celsius

temp_mean = temp.mean(dim=["latitude", "longitude"])

monthly_temp = temp_mean.groupby("valid_time.month").mean()

plt.figure(figsize=(10,6))

plt.plot(
    monthly_temp["month"],
    monthly_temp.values,
    linewidth=2,
    marker="o"
)

plt.xlabel("Month")
plt.ylabel("Temperature (°C)")
plt.title("Figure 7.4 Monthly Mean Temperature Trends\nSouth Caucasus (ERA5 2025)")
plt.grid(True)

plt.savefig("figure_7_4_temperature_trends.png", dpi=300, bbox_inches="tight")
plt.show()

from google.colab import files
files.download("figure_7_4_temperature_trends.png")

"""#7.5 - Hydroclimatic Dataset Comparison South Caucasu"""

import matplotlib.pyplot as plt
import numpy as np

ds_precip = xr.open_dataset(
    "./era5_2025/data_stream-oper_stepType-accum.nc"
)

ds_temp = xr.open_dataset(
    "./era5_2025/data_stream-oper_stepType-instant.nc"
)

precip = ds_precip["tp"] * 1000      # mm
temp = ds_temp["t2m"] - 273.15       # Celsius

precip_mean = precip.mean(dim=["latitude", "longitude"])
temp_mean = temp.mean(dim=["latitude", "longitude"])

monthly_precip = precip_mean.groupby("valid_time.month").mean()
monthly_temp = temp_mean.groupby("valid_time.month").mean()

fig, ax1 = plt.subplots(figsize=(11,6))

ax1.plot(
    monthly_precip["month"],
    monthly_precip.values,
    linewidth=2,
    marker="o",
    label="Precipitation"
)

ax1.set_xlabel("Month")
ax1.set_ylabel("Precipitation (mm)")

ax2 = ax1.twinx()

ax2.plot(
    monthly_temp["month"],
    monthly_temp.values,
    linewidth=2,
    marker="s",
    linestyle="--",
    label="Temperature"
)

ax2.set_ylabel("Temperature (°C)")

plt.title(
    "Figure 7.5 Hydroclimatic Dataset Comparison\nSouth Caucasus (ERA5 2025)",
    fontsize=14
)

plt.grid(True)

plt.savefig(
    "figure_7_5_dataset_comparison.png",
    dpi=300,
    bbox_inches="tight"
)

plt.show()

from google.colab import files
files.download("figure_7_5_dataset_comparison.png")

import cdsapi

client = cdsapi.Client()

client.retrieve(
    "reanalysis-era5-single-levels",
    {
        "product_type": "reanalysis",

        "variable": [
            "evaporation"
        ],

        "year": ["2025"],

        "month": [
            "01", "02", "03", "04", "05", "06",
            "07", "08", "09", "10", "11", "12"
        ],

        "day": [
            "01", "02", "03", "04", "05", "06", "07", "08", "09", "10",
            "11", "12", "13", "14", "15", "16", "17", "18", "19", "20",
            "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31"
        ],

        "time": [
            "00:00",
            "06:00",
            "12:00",
            "18:00"
        ],

        "area": [43, 38, 38, 51],

        "data_format": "netcdf",
        "download_format": "unarchived"
    },

    "era5_evaporation_2025.nc"
)

"""#7.6 Monthly Evaporation Variability South Caucasus"""

import xarray as xr

ds_evap = xr.open_dataset("era5_evaporation_2025.nc")

print(ds_evap)
print(ds_evap.data_vars)

import matplotlib.pyplot as plt

evap = ds_evap["e"] * 1000

evap_mean = evap.mean(dim=["latitude", "longitude"])

monthly_evap = evap_mean.groupby("valid_time.month").mean()

plt.figure(figsize=(10,6))

plt.plot(
    monthly_evap["month"],
    monthly_evap.values,
    linewidth=2,
    marker="o"
)

plt.xlabel("Month")
plt.ylabel("Evaporation (mm)")

plt.title(
    "Figure 7.6 Monthly Evaporation Variability\nSouth Caucasus (ERA5 2025)",
    fontsize=14
)

plt.grid(True)

plt.savefig(
    "figure_7_6_evaporation_variability.png",
    dpi=300,
    bbox_inches="tight"
)

plt.show()

from google.colab import files
files.download("figure_7_6_evaporation_variability.png")

"""#7.7 Atmospheric Water Budget Variability South Caucasus"""

import matplotlib.pyplot as plt

ds_precip = xr.open_dataset(
    "./era5_2025/data_stream-oper_stepType-accum.nc"
)


precip = ds_precip["tp"] * 1000

evap = ds_evap["e"] * 1000

precip_mean = precip.mean(dim=["latitude", "longitude"])
evap_mean = evap.mean(dim=["latitude", "longitude"])

monthly_precip = precip_mean.groupby("valid_time.month").mean()
monthly_evap = evap_mean.groupby("valid_time.month").mean()

water_budget = monthly_precip - monthly_evap

plt.figure(figsize=(10,6))

plt.plot(
    monthly_precip["month"],
    water_budget.values,
    linewidth=2,
    marker="o"
)

plt.axhline(0, linestyle="--")

plt.xlabel("Month")
plt.ylabel("P - E (mm)")

plt.title(
    "Figure 7.7 Atmospheric Water Budget Variability\nSouth Caucasus (ERA5 2025)",
    fontsize=14
)

plt.grid(True)

plt.savefig(
    "figure_7_7_water_budget.png",
    dpi=300,
    bbox_inches="tight"
)

plt.show()

from google.colab import files
files.download("figure_7_7_water_budget.png")

"""#7.8 Computational Workflow for ERA5 Hydroclimatic Analysis"""

import matplotlib.pyplot as plt
from matplotlib.patches import FancyBboxPatch

steps = [
    "ERA5 Data\nDownload",
    "NetCDF\nExtraction",
    "Variable\nSelection",
    "Preprocessing\n& Cleaning",
    "Temporal\nAggregation",
    "Climate\nDiagnostics",
    "Visualization\n& Figures",
    "Report\nInterpretation"
]

fig, ax = plt.subplots(figsize=(14, 4))
ax.set_xlim(0, len(steps))
ax.set_ylim(0, 1)
ax.axis("off")

for i, step in enumerate(steps):
    box = FancyBboxPatch(
        (i + 0.1, 0.35),
        0.8,
        0.3,
        boxstyle="round,pad=0.04",
        linewidth=1.5,
        facecolor="white",
        edgecolor="black"
    )
    ax.add_patch(box)

    ax.text(
        i + 0.5,
        0.5,
        step,
        ha="center",
        va="center",
        fontsize=10
    )

    if i < len(steps) - 1:
        ax.annotate(
            "",
            xy=(i + 1.05, 0.5),
            xytext=(i + 0.9, 0.5),
            arrowprops=dict(arrowstyle="->", linewidth=1.5)
        )

plt.title(
    "Figure 7.8 Computational Workflow for ERA5 Hydroclimatic Analysis",
    fontsize=14
)

plt.savefig(
    "figure_7_8_computational_workflow.png",
    dpi=300,
    bbox_inches="tight"
)

plt.show()

from google.colab import files
files.download("figure_7_8_computational_workflow.png")